### ISSUE TITLE
问问

### ISSUE THREAD

**Issue by Klosw** [Curtion/douyu-keep#1]
有时候会掉登陆，点重新登录（不需要登录） ， 关闭后才能继续 ，这种怎么解决

**Comment by Curtion** [comment]
找到原因了, 本周修复

**Comment by Klosw** [comment]
> 找到原因了, 本周修复

修好了吗

**Comment by Curtion** [comment]
> > 找到原因了, 本周修复
> 
> 修好了吗

我之前遇到过一次，但是没有再复现过，所以原因还不明。 如果下次遇到了麻烦右键退出软件，然后重写打开软件试试是否正常。 我怀疑是软件自动启动时电脑的网络还没有准备好导致的

**Comment by Klosw** [comment]
> > > 找到原因了, 本周修复
> > 
> > 
> > 修好了吗
> 
> 我之前遇到过一次，但是没有再复现过，所以原因还不明。 如果下次遇到了麻烦右键退出软件，然后重写打开软件试试是否正常。 我怀疑是软件自动启动时电脑的网络还没有准备好导致的

你的意思是 网络还没好的情况下无法校验 token是否过期是这个意思吗 , 导致需要登录是吗

**Comment by Curtion** [comment]
已经修复, 下载最新的版本的应该不会出现该现象了
