### ISSUE TITLE
winserver2012标准版打开程序显示无法找到入口

### ISSUE THREAD

**Issue by 2291109502** [Curtion/douyu-keep#10]
![chrome_yT0OCWR0jo](https://github.com/user-attachments/assets/c53fb091-e36d-4ad3-8e4f-14a333dba7c6)
百度的话是有缺少Kernel32.dll的解决方案，但是这里报错不一样，不太清楚怎么解决。

是需要补充安装什么运行库吗？还是系统内核版本不对？如果太麻烦也无所谓。

**Comment by Curtion** [comment]
查了一下，说是`electron 23`以上放弃了windows7的支持,  我这里降低版本进行了一个打包, 但是没有条件进行测试，你可以测试一下有没有问题。 后续你也可以自己降低版本构建试试。
https://wws.lanzoub.com/i62IP2fs545a

**Comment by 2291109502** [comment]
实机测试后以及可以正常使用。非常干线
