### ISSUE TITLE
建议增加一个领取不赠送的功能

### ISSUE THREAD

**Issue by maoshibai** [Curtion/douyu-keep#8]
这样可以屯到周末送亲密度高一点

**Comment by Curtion** [comment]
亲密度是周末一定更高吗？ 还是说每个主播都不同？  如果一定是周末更高可以新增一个存到周末再送的配置，但是如果每个主播都不同就不太好做。

**Comment by maoshibai** [comment]
> 亲密度是周末一定更高吗？ 还是说每个主播都不同？ 如果一定是周末更高可以新增一个存到周末再送的配置，但是如果每个主播都不同就不太好做。

不是一定更高，斗鱼有个超级粉丝团的任务，一般大主播都能完成，完成了周末就有1.5倍亲密度。。我是想着如果可以只领取不赠送就好了，具体哪天送可以用户自己用Cron表达式嘛
